//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamManageSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamPaper
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string Examinee { get; set; }
        public Nullable<int> Score { get; set; }
        public string WrongId { get; set; }
        public Nullable<int> WrongScore { get; set; }
        public Nullable<int> UsageCount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
